### ISSUE TITLE
[Feature Request]  Uptime kuma

### ISSUE THREAD

**Issue by finnie2006** [benphelps/homepage#367] opened 2022-10-10 08:32 UTC
**Is your feature request related to a service? Please describe.**
Add a service widget for uptime kuma, uptime kuma is uptime monitoring software, for example:
In the widget you could add  down monitors up monitors etc...

**Is your feature request related to a problem? Please describe.**
X
**Additional context**
X

**Comment by JazzFisch** [comment] 2022-10-11 07:41
This is a duplicate of #123.

**Closed by JazzFisch** 2022-10-11 07:41 UTC
