### ISSUE TITLE
[help wanted] Pi-Hole Widget shows stats as "NaN"

### ISSUE THREAD

**Issue by sankethguru** [benphelps/homepage#718] opened 2022-12-23 04:10 UTC
Hi, 
After i updated Pi-Hole to v5.14.2, Homepage container to v0.5.5 and hitting reload icon at the bottom of the Homepage webpage, Pi-Hole stats in the widget shows "NaN". 
Have tried:
1. Rebooting Homepage container.
2. Rebooting Portainer (Homepage runs here).
3. Rebooting Pi-Hole.
4. Flushed Query Logs of Pi-Hole.
5. Removed Pi-Hole and re-added the same in Services.yaml.

These do not help fix the issue. Is this a bug or am I doing something wrong?

![image](https://user-images.githubusercontent.com/77433101/209269335-62734d3e-c17a-4ac7-b7cb-1c7ad32c274b.png)

The other widgets work fine:
![image](https://user-images.githubusercontent.com/77433101/209269725-16582163-8850-49a2-8830-03d04922817c.png)

**Comment by shamoon** [comment] 2022-12-23 05:19
duplicate of #717, #711

**Closed by shamoon** 2022-12-23 05:19 UTC
