### ISSUE TITLE
[Bug] Error: Invalid argument not valid semver ('homepage-0.1.0' received)

### ISSUE THREAD

**Issue by MarcelBochtler** [benphelps/homepage#1055] opened 2023-02-24 19:42 UTC
### Description

Since some minutes I'm getting this error on my homepage installed on unRAID.

```
Something went wrong.
Error: Invalid argument not valid semver ('homepage-0.1.0' received)

f@http://home.box/_next/static/chunks/1824.1488cfcd10078c95.js:1:1097
5589/y/h<@http://home.box/_next/static/chunks/8851-2e733d9d318b32dc.js:1:12200
div
div
re@http://home.box/_next/static/chunks/pages/index-b0336bb32f0d5969.js:1:39627
n@http://home.box/_next/static/chunks/pages/index-b0336bb32f0d5969.js:1:9932
6747/Y<@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:88003
te@http://home.box/_next/static/chunks/pages/index-b0336bb32f0d5969.js:1:37679
div
div
ie@http://home.box/_next/static/chunks/pages/index-b0336bb32f0d5969.js:1:43515
a@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:15039
s@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:15596
u@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:14471
6747/Y<@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:88003
6207/t.default<@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:13752
l@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:1459
n@http://home.box/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:5969
r@http://home.box/_next/static/chunks/main-d2b206db40ae9853.js:1:6949
Y@http://home.box/_next/static/chunks/main-d2b206db40ae9853.js:1:9188
ie@http://home.box/_next/static/chunks/main-d2b206db40ae9853.js:1:11828
```

### Steps to reproduce

1. Install homepage
2. Open the web UI

### homepage version

Docker latest

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment] 2023-02-24 19:43
Duplicate of #1049

**Closed by shamoon** 2023-02-24 19:43 UTC
Labels: bug
