### ISSUE TITLE
[Bug] Memory not displaying on docker container expanded info

### ISSUE THREAD

**Issue by philhagger** [benphelps/homepage#142] opened 2022-09-13 10:14 UTC
![portainer-docker](https://user-images.githubusercontent.com/739206/189875701-ec271dbd-3deb-4b25-be2d-088d54118da2.png)

All of my docker containers show the following on memory: `{{value, bytes}}`

**Comment by benphelps** [comment] 2022-09-13 10:45
I'd try restarting the container or updated to the latest tag.  I've never seen this before, it looks like you're having issues with the i18n support.

What language is browser defaulting to?

**Comment by C8opmBM** [comment] 2022-09-13 14:02
Sorry to bumb, but can you tell me what do one needs to pass in the widget to get the expanded info? I only have the bottom row visible. Thanks

**Comment by benphelps** [comment] 2022-09-13 17:46
You can expand the stats by clicking on the status light.

**Comment by C8opmBM** [comment] 2022-09-14 17:37
I don't have any status light... is this a bug?

![111](https://user-images.githubusercontent.com/60513190/190224372-ef9f55c1-e88e-4ad4-bd57-67cb42e9b386.jpg)

**Comment by hunkyn** [comment] 2022-09-17 00:17
@C8opmBM have you enabled docker integration? Here is an example from wiki on docker integration

https://github.com/benphelps/homepage/wiki/Docker-Integration

**Comment by colutti** [comment] 2022-09-17 15:03
I have the same issue. homepage is running in a PI2 with portainer and pihole. I had another [issue](https://github.com/benphelps/homepage/issues/196) that the docker integration was not working. I am on Fedora, firefox and my language is set to pt-BR.

![image](https://user-images.githubusercontent.com/9368892/190863484-cd8faedd-4740-4891-968c-8b8a2ab8512e.png)

**Comment by madkatz01** [comment] 2022-09-17 18:08
I likewise have the same issue  for the memory box. Any fixes?

**Comment by DanJackiels** [comment] 2022-09-21 00:49
I also have the same issue. Raspberry Pi 4 64-bit.
I tried the following browsers: Chrome, Firefox, Brave, and Android Chrome. It's all the same on all of them.

Another minor issue is that the little house icon won't load on Firefox and Android Chrome, and I get a blank white icon or the default on Firefox.

**Comment by al-jimenez** [comment] 2022-09-27 17:53
I also have this issue on Raspberry Pi 4B 64bit;  All docker containers listed with widgets are showing {{value, bytes}} for MEM.  Tried several different configuration attempts but all other indices show up fine.

**Comment by benphelps** [comment] 2022-09-27 17:58
So this just came to me, I'm pretty sure I know what the problem is,

On the pi, try these steps:

1. Edit this file, `sudo nano /boot/cmdline.txt`
2. Add these options, `cgroup_enable=memory cgroup_memory=1`
3. Reboot the pi, `sudo reboot now`

Let me know if that fixes it.

**Comment by madkatz01** [comment] 2022-09-27 18:12
Unfortunately this made no difference in my setup, but I appreciate you looking into it! It does appear to be only related to my raspberry pi's (all 64-bit, running Raspian OS)

**Comment by benphelps** [comment] 2022-09-27 18:20
My understanding is, it enables process memory control (limiting, detailed monitoring, etc).  It's disabled on Pi's by default since it adds a bit of memory overhead, but is required for Docker to report memory usage stats.

You can read about cgroups here: https://en.wikipedia.org/wiki/Cgroups

**Comment by al-jimenez** [comment] 2022-09-27 21:20
This did it for me also ❗️  Thanks very much for this.   Great work to you and everyone else on this dashboard.

**Comment by JazzFisch** [comment] 2022-09-28 17:07
Thanks al-jimenez.  I'm going to close this issue.  Please re-open as needed.

**Closed by JazzFisch** 2022-09-28 17:07 UTC
