### ISSUE TITLE
[Topic] Layout & Positioning Issues

### ISSUE THREAD

**Issue by benphelps** [benphelps/homepage#235] opened 2022-09-20 17:41 UTC
This issue will serve as a single point of discussion for anything related to layout or positioning issues, bugs, suggestions, etc.

**Comment by AmadeusGraves** [comment] 2022-09-20 20:20
CUSTOM CSS 
Apart from the .yml files that exist in the configuration folder, a css class could also be instantiated to allow editing of the page style. This way the developer will be more free from design issues like on certain wallpapers with certain colours, it is not possible to read the data displayed on the screen.

**Comment by Spiritreader** [comment] 2022-09-21 21:09
It would be wonderful to be able to display a custom logo to the left of the resource monitoring information.
![image](https://user-images.githubusercontent.com/18438899/191610769-ef0fd104-0af6-46c0-888e-674039d61e0f.png)

**Comment by ysarkain** [comment] 2022-09-25 02:49
2 requests:
1) Adjustable width of page - on my 2560x1440 monitor it looks like its ~75% so there is lots of space on both sides.
2) Also would be cool if we could put the speedtest widget in the header bar area with the disk/cpu/etc. statistics.

**Comment by iamernie** [comment] 2022-10-05 14:27
> Hi, could you please tell me how I can get this layout config?
> 
> <img alt="190466646-8ca94505-0fcf-4964-9687-3a6c7cd3144f" width="1260" src="https://user-images.githubusercontent.com/106855541/193499239-1969527e-b44b-4459-af4a-b4c86f4f762c.png">
> 
> I have the current layout settings in my yml file:
> 
> layout: Media: style: row columns: 4 Downloads: style: row columns: 1 Utilities: style: row columns: 1
> 
> I have tried a few different variations of the above, but nothing that will replicate the above picture :(

Try this:
layout:
Media:
style: row
columns: 4
Downloads:
style: column
Utilities:
style: column

**Comment by dieideeistgut** [comment] 2022-10-06 21:25
Heya. Please don't over-complicate this one. I'd vote for a simple single-css-file-include via volume/bind. If there is no file, there will be nothing included.

**Comment by chuckiton** [comment] 2022-10-12 13:52
<img width="1568" alt="Screenshot 2022-10-12 at 14 51 06" src="https://user-images.githubusercontent.com/90910365/195360997-27706564-e8dc-4af7-8f49-e83f6c32a541.png">
Search bar doesn't extend to the boundary of the date/time info widget
Contents of widgets.yaml:
```
- resources:
    label: System
    cpu: true
    memory: true
- resources:
    label: mSD Storage
    disk: /
- resources:
    label: Disk Storage
    disk: /mnt/storage
- search:
    provider: duckduckgo # google, duckduckgo, bing or custom
    target: _blank
    focus: true
# 1/23/22, 1:37 PM
- datetime:
    format:
        dateStyle: short
        timeStyle: short
        hour12: true
```

**Comment by EnsuingRequiem** [comment] 2022-10-18 20:20
Similar to how the number of `columns` can be defined when using `style: row` which causes wrapping once the number of columns is exceeded, a `rows` option should be available for `style: column` to allow for "wrapping" once the limit of rows is met. I would expect it to look like

```
layout:
  Management:
    style: column
    rows: 4
  Media:
    style: row
    columns: 4
```

Which (ascii-like) would look like
```
Media
┌─────────┐┌─────────┐┌─────────┐┌─────────┐
│         ││         ││         ││         │
│         ││         ││         ││         │
└─────────┘└─────────┘└─────────┘└─────────┘
┌─────────┐
│         │
│         │
└─────────┘
Management
┌─────────┐┌─────────┐
│         ││         │
│         ││         │
└─────────┘└─────────┘
┌─────────┐
│         │
│         │
└─────────┘
┌─────────┐
│         │
│         │
└─────────┘
┌─────────┐
│         │
│         │
└─────────┘
```

**Comment by Samurai1201** [comment] 2022-10-21 06:27
Ive been using Homer (https://github.com/bastienwirtz/homer) previously.
It has the option to define how many columns should be arranged next to each other.

You just had to set this option in the config yaml: 
`columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)`
and it would format the page accordingly.

I would really love to see this being implemented into hompage.

**Comment by frozendark01** [comment] 2022-10-21 07:20
Hello,
I don't know how react-next.js works, but is it possible to create a header like this? I think it is much more organized and aligned.
![image](https://user-images.githubusercontent.com/42968687/197136090-fe2de8eb-fa13-4f1a-a808-481e703df2c2.png)

**Comment by brhahlen** [comment] 2022-10-21 08:48
Just discovered this two days ago and liking it really much already. Especially the Docker integration with labels!
Many kudos!

Probably on your list already (but couldn't find it mentioned specifically), but my main "gripe" right now is that I can't order things myself.

This not only goes for the different sections, which seem to order "randomly", but also for the items within the sections.

Thanks for all your hard work!

**Comment by Nonoss117** [comment] 2022-10-21 10:04
@brhahlen 
you can find details about ordering in the wiki : https://github.com/benphelps/homepage/wiki/Service-Discovery/#caveats

**Comment by brhahlen** [comment] 2022-10-21 11:24
@Nonoss117 Thanks! I've seen that and am aware of it.
Just saying it would be great to be able to order it yourself. Maybe via a label or something, there must be some way to realize that :)

**Comment by Mivaro482** [comment] 2022-10-26 15:55
Since one the recent versions, the bookmarks columns have no spacing - I just defined three columns of bookmarks and no further config. 
![image](https://user-images.githubusercontent.com/24875176/197995105-f02dc791-544b-41ea-b217-fbd97939f1bf.png)

**Comment by shamoon** [comment] 2022-10-26 16:57
Fixed the above =)

<img width="1269" alt="Screen Shot 2022-10-26 at 9 56 26 AM" src="https://user-images.githubusercontent.com/4887959/198088398-0475c8ee-7dba-4ed4-a160-2cf407c6b7d8.png">

**Comment by gDansel** [comment] 2022-11-03 13:34
![image](https://user-images.githubusercontent.com/83411026/199734303-127e87bd-9383-4ce6-b246-d21360b7d3c3.png)
Might be neat if an entry with associated widget enabled had the same height as two normal entries. You know, to keep things aligned nicely. Couple of pixels off at the moment.

**Comment by szczottie** [comment] 2022-11-11 18:07
> Ive been using Homer (https://github.com/bastienwirtz/homer) previously. It has the option to define how many columns should be arranged next to each other.
> 
> You just had to set this option in the config yaml: `columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)` and it would format the page accordingly.
> 
> I would really love to see this being implemented into hompage.

Also looking for this.

**Comment by smit-io** [comment] 2022-11-12 17:55
I am getting API error when I try to see the storage on mounted devices. Any help is appreciated.
widgets.yaml file and screenshot attached.
![widgets](https://user-images.githubusercontent.com/113954709/201487943-2e6e96f7-deb8-4afe-9451-b3925457b511.png)
![homepage](https://user-images.githubusercontent.com/113954709/201487945-c16d809c-473b-4e32-a56a-f428c274c1e1.png)

**Comment by lsaadeh** [comment] 2022-11-14 06:13
Can we have these float upward to avoid blank spaces? (Half screen mode)
![image](https://user-images.githubusercontent.com/43462320/201588272-09b259c3-0dca-4372-aa60-33df849c69e9.png)

**Comment by stephentoth** [comment] 2022-12-13 23:14
There seems to be an issue with the greeting in the header.
![image](https://user-images.githubusercontent.com/11590186/207465330-fce78977-6312-4003-a29e-ead7598db029.png)

```
- greeting:
    text_size: xl
    text: "The Vault"

- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hour12: false

- search:
    provider: duckduckgo
    target: _blank
```

**Comment by UmarAbdullah4** [comment] 2023-01-03 08:00
I can fit it but I don't know how to contribute in this project

**Comment by Beguiled** [comment] 2023-01-23 18:43
I just upgraded to 0.6.3 (c74b467, Jan 22, 2023) and now all of my services are laid out in columns, as compared to their row definitions.

For example:
```yaml
layout:
  Network:
    style: row
    columns: 4
```

This is supposed to display the services horizontally, 4 services per row. At this time the services are showing up in a vertical column instead, with the four services stacked vertically:
![image](https://user-images.githubusercontent.com/7060159/214122786-43a58321-855d-4aad-b77b-439a62799987.png)

This was not present with my previous build which was a bit outdated. (0.5.x)

**Comment by JazzFisch** [comment] 2023-01-25 01:45
> I can fit it but I don't know how to contribute in this project

If you have ideas on how to improve the styling, you can either post examples, or go ahead and clone the repo and make a PR.  Feel free to ask questions if you need help.

**Comment by Stuke00** [comment] 2023-01-29 13:16
My layout keeps reverting back to columns even when my settings.yaml indicate rows.  If I just open the file and resave it, it will revert back to rows.  Here is my settings.yaml file (renamed to txt so I could upload).  I've also attached 2 files showing the difference.  

![Screenshot 2023-01-29 071140](https://user-images.githubusercontent.com/16128402/215328704-923412c2-0d17-4660-814d-79837ef00a73.png)
![Screenshot 2023-01-29 071547](https://user-images.githubusercontent.com/16128402/215328703-737d2640-7b7d-4066-b7a4-46a13ef836e5.png)

[settings.txt](https://github.com/benphelps/homepage/files/10529823/settings.txt)

**Comment by Beguiled** [comment] 2023-01-29 13:41
> My layout keeps reverting back to columns even when my settings.yaml indicate rows. If I just open the file and resave it, it will revert back to rows. Here is my settings.yaml file (renamed to txt so I could upload). I've also attached 2 files showing the difference.
> 
> ![Screenshot 2023-01-29 071140](https://user-images.githubusercontent.com/16128402/215328704-923412c2-0d17-4660-814d-79837ef00a73.png) ![Screenshot 2023-01-29 071547](https://user-images.githubusercontent.com/16128402/215328703-737d2640-7b7d-4066-b7a4-46a13ef836e5.png)
> 
> [settings.txt](https://github.com/benphelps/homepage/files/10529823/settings.txt)

Same happened to me after an upgrade to a newer version. Try clearing your cache or force-refreshing it. One of those should clear it up.

**Comment by rursache** [comment] 2023-01-30 16:09
> Adjustable width of page - on my 2560x1440 monitor it looks like its ~75% so there is lots of space on both sides.

I would also like this. 5 columns instead of 4 would be nice

**Comment by ashanrath** [comment] 2023-01-31 04:58
Also experiencing the same layout issues after the latest version. Favicon and background images also appear to have broken. Have attempted cache clearing, multiple PCs etc. No resolution at the moment.

**Comment by BigJazzz** [comment] 2023-02-01 00:00
Two issuess:
1. I put time above resources in the yaml file, but it still shows on the right
2. It doesn't seem to adhere to the text size? I've tried changing it, but it just seems to be consistently one size

Is there something I'm missing?

widgets.yaml:
```yaml
- datetime:
    locale: au
    text_size: 4x1
    format:
        timeStyle: short
        hour12: false
        dateStyle: short

- resources:
    cpu: true
    memory: true
    disk: /
```
![image](https://user-images.githubusercontent.com/2503113/215911455-b504c75f-aeaf-4edf-8385-6aa9664aaf84.png)

**Comment by Beguiled** [comment] 2023-02-01 00:04
> ```yaml
> 4x1
> ```

I’m seeing `4x1` on your `text_size` definition. Try `4xl` instead. You might have confused the `l` with a `1`.

**Comment by BigJazzz** [comment] 2023-02-01 00:06
@Beguiled that did the trick, thank you! And I did. Probably should've just copy/pasted to avoid that issue. -.-

**Comment by Beguiled** [comment] 2023-02-01 00:08
Glad I could help! It’s easy to make that mistake - you’re not alone!

**Comment by eanmclaughlin** [comment] 2023-02-01 19:27
@BigJazzz The header widgets are added here: https://github.com/benphelps/homepage/blob/147a165bbcc28bdb50b0f3842a717e4a4dd626c3/src/pages/index.jsx#L273-L284

Looks like there's a concept of "right-aligned" and "not right aligned"; the right-aligned ones are listed here: https://github.com/benphelps/homepage/blob/147a165bbcc28bdb50b0f3842a717e4a4dd626c3/src/pages/index.jsx#L39

I think ordering support for them would require adding a sort/weight/order field, and probably include fallback to the existing alignment-based setup if that new field isn't defined?

**Comment by BigJazzz** [comment] 2023-02-01 20:03
@eanmclaughlin Oooooh. Maybe I might have a play wtih this. Thanks for that!

**Comment by simeonrobinson** [comment] 2023-02-02 04:22
Is it possible to explicitly specify two links be stacked next to a widget like in this image? 
![example](https://user-images.githubusercontent.com/72761033/216229137-4b9cb92d-621a-4d3e-bbd7-8366d048724a.png)
Currently my services.yaml looks something like this: 
 
```
 - Utilities:
  -  Pi-hole stats:

        icon: pihole.png
        href: xxxx
        widget:
            type: pihole
            url: xxxx
            key: xxxx
    - Unraid dashboard:

        icon: unraid.png
        href: xxxx
    - EdgeOS dashboard:

        icon: edgeos-light.png
        href: xxxx

```
and settings.yaml looks like this:
```
  Utilities:
    style: row
    columns: 2
```
producing this 
![current](https://user-images.githubusercontent.com/72761033/216230213-5a2f51a0-72e6-4e5b-a15c-10eb19fa9fee.png)

**Comment by itsthejb** [comment] 2023-02-02 11:48
On starting the Homepage container, the layout will be incorrect; it seems like the rows/columns settings aren't correctly used:

<img width="1233" alt="Screenshot 2023-02-02 at 11 42 57" src="https://user-images.githubusercontent.com/557391/216316144-efb8d19f-f0b7-47f2-9184-25381d1d0ca0.png">

Notice the 3 columns. The configured layout is actually:

<img width="1253" alt="Screenshot 2023-02-02 at 11 44 31" src="https://user-images.githubusercontent.com/557391/216316234-1cbd8469-3d5a-4f7f-b568-cffeebad0e8d.png">

I can fix this issue once the container is running by doing a minor edit to any of the configs, letting the layout reload, and then undoing the change.

It would appear that the only problem is that the row/column settings aren't correctly set up on the initial load. Any changes after that are fine

Relevant config snippet:

```
layout:
  Media:
    icon: mdi-video
    style: row
    columns: 2
  Productivity:
    icon: mdi-briefcase
    style: row
    columns: 3
  Infrastructure:
    icon: mdi-hammer-wrench
    style: column
```

**Comment by Beguiled** [comment] 2023-02-02 11:54
You’re the third person here recently to mention that, and I think you have produced the clearest picture of the scenario. I thought I had just refreshed and things worked again but I think you are right in that it requires a modification to the configs. This must have been introduced with a recent build.

**Comment by itsthejb** [comment] 2023-02-02 11:56
Happy to help. I think the background image is also affected

**Comment by shamoon** [comment] 2023-02-02 14:52
This is the same bug I tried to fix in #609 , unfortunately it would seem that didn’t really do it. It’s a bizarre one. I reopened #576

**Comment by ashanrath** [comment] 2023-02-07 03:49
> Happy to help. I think the background image is also affected

Confirmed, tried making a minor change to a config file after the container had started, layout issues fixed, background and favicon images also fixed. It's definitely something with the initial load. Guessing most of us associated it with the upgrade as that's when we last restarted the container.

**Comment by cinderblockgames** [comment] 2023-03-04 14:55
> My layout keeps reverting back to columns even when my settings.yaml indicate rows. If I just open the file and resave it, it will revert back to rows. Here is my settings.yaml file (renamed to txt so I could upload). I've also attached 2 files showing the difference.
> 
> ![Screenshot 2023-01-29 071140](https://user-images.githubusercontent.com/16128402/215328704-923412c2-0d17-4660-814d-79837ef00a73.png) ![Screenshot 2023-01-29 071547](https://user-images.githubusercontent.com/16128402/215328703-737d2640-7b7d-4066-b7a4-46a13ef836e5.png)
> 
> [settings.txt](https://github.com/benphelps/homepage/files/10529823/settings.txt)

Came here to report this as well.  It keeps happening.

**Comment by joestump** [comment] 2023-03-25 16:18
Any way to make these widgets line up? It's driven me a little nuts 😅 

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/37667/227729167-6fc4faa2-0c15-4cec-baa3-479a3d3b379d.png">

**Comment by shamoon** [comment] 2023-04-07 19:35
If it’s happening on refresh there’s an issue with your setup. The bug the other user described was fixed in the last version

**Comment by Robin-Sch** [comment] 2023-04-12 17:01
I have 6 "groups" each one has `style: column`

So right now it orders like this:
1 2 3 4 
5 5 6 6
(5 and 6 are twice as wide as 1 etc..)

is it possible to have it split in three? so like
1 2 3
4 5 6

**Comment by UmarAbdullah4** [comment] 2023-04-12 17:41
Yes its possible

**Comment by UmarAbdullah4** [comment] 2023-04-14 09:24
To achieve this, you'll need to modify the CSS for the columns. Here's an
example CSS that should achieve the desired layout:

.column {
  width: 33.33%;
  float: left;
}

.group1 {
  clear: left;
}

.group2 {
  margin-left: 33.33%;
}

.group3 {
  margin-left: 66.66%;
}

In this CSS, the .column class sets each column to be 33.33% wide and float
left. The .group1, .group2, and .group3 classes set the position of the
columns within each group.

To use this CSS, you'll need to add the appropriate classes to each column.
For example, the first three columns would have the class column group1,
the next two would have the class column group2, and the last column would
have the class column group3.

With this CSS and class setup, the columns should display in the order you
described:


1 2 3
4 5 6

I hope this helps!

**Comment by crispybegs** [comment] 2023-04-15 14:43
> Can we have these float upward to avoid blank spaces? (Half screen mode) ![image](https://user-images.githubusercontent.com/43462320/201588272-09b259c3-0dca-4372-aa60-33df849c69e9.png)

very much this. did you ever find a solution to it? those big gaps drive me crazy.

<img width="822" alt="Screenshot 2023-04-15 at 15 42 46" src="https://user-images.githubusercontent.com/129169122/232231182-8cb4afca-4bdd-44a5-9714-7e8fb731360e.png">

**Comment by jinghua625** [comment] 2023-04-18 15:00
i
![4ac92470215d6d1ff6243d2a8de52c7](https://user-images.githubusercontent.com/97967510/232818407-572d399f-3532-42c3-ae45-7c5866022cae.png)

**Comment by crispybegs** [comment] 2023-04-18 15:24
I'm being thick. Can anyone give an example of where to put the code to implement the five columns option?
and bonus points if you can paste a screenshot of the five columns in action.

<img width="730" alt="Screenshot 2023-04-18 at 16 22 58" src="https://user-images.githubusercontent.com/129169122/232825070-194f5e19-37a2-42ba-a65a-ab24fa0fcd6f.png">

**Comment by vxav** [comment] 2023-04-21 11:02
In the kubernetes integration, could we change the status (e.g. `RUNNING`) to a dot like the Docker integration? Looks slicker imo.
It could also be a flag in `kubernetes.yaml` ?

![image](https://user-images.githubusercontent.com/19745768/233620448-b7405930-6d28-4bcc-afad-536ba8957923.png)

**Comment by null-except** [comment] 2023-04-21 16:03
> I'm being thick. Can anyone give an example of where to put the code to implement the five columns option? and bonus points if you can paste a screenshot of the five columns in action.
> 
> <img alt="Screenshot 2023-04-18 at 16 22 58" width="730" src="https://user-images.githubusercontent.com/129169122/232825070-194f5e19-37a2-42ba-a65a-ab24fa0fcd6f.png">

Just add this line in settings.yaml. Here a screenshot : 

![image](https://user-images.githubusercontent.com/85898436/233682682-d9165013-9dc9-4fb9-a063-bcdf4eb96fd3.png)

**Comment by crispybegs** [comment] 2023-04-24 22:12
what am i getting wrong here?

i want the 'RPIs' column to appear _before_ the 'Usenet' and 'Hubs' column

<img width="1060" alt="Screenshot 2023-04-24 at 23 08 40" src="https://user-images.githubusercontent.com/129169122/234127523-a12a610b-e2f6-4d2c-9925-0e92187c7522.png">

my yaml looks like this, but no matter how many times i adjust it and save it the columns won't switch...

<img width="568" alt="Screenshot 2023-04-24 at 23 09 27" src="https://user-images.githubusercontent.com/129169122/234127638-d505a5ab-5c3d-49d0-a7fa-0300d92846b4.png">

First time this hasn't worked for me. What am I getting wrong?

**Comment by crispybegs** [comment] 2023-04-25 10:47
> I'm being thick. Can anyone give an example of where to put the code to implement the five columns option? and bonus points if you can paste a screenshot of the five columns in action.
> 
> <img alt="Screenshot 2023-04-18 at 16 22 58" width="730" src="https://user-images.githubusercontent.com/129169122/232825070-194f5e19-37a2-42ba-a65a-ab24fa0fcd6f.png">

ignore this, of course i forgot you have to amend the settings.yaml rather than just move stuff around in services. because i'm a cretin.

**Comment by juanmanuelbc** [comment] 2023-04-26 08:31
> ![image](https://user-images.githubusercontent.com/83411026/199734303-127e87bd-9383-4ce6-b246-d21360b7d3c3.png) Might be neat if an entry with associated widget enabled had the same height as two normal entries. You know, to keep things aligned nicely. Couple of pixels off at the moment.

If `mb-3` was changed to `mb-2` that should be `margin-bottom: .5rem` (instead of `margin-bottom: .75rem`) then we would get the trick to accomplish this alignment...

I'll search the way to make this change and put a PR, but I can't promise anything...

**Comment by juanmanuelbc** [comment] 2023-04-27 09:18
> > ![image](https://user-images.githubusercontent.com/83411026/199734303-127e87bd-9383-4ce6-b246-d21360b7d3c3.png) Might be neat if an entry with associated widget enabled had the same height as two normal entries. You know, to keep things aligned nicely. Couple of pixels off at the moment.
> 
> I'll search the way to make this change and put a PR, but I can't promise anything...

PR https://github.com/benphelps/homepage/pull/1419 done...

**Comment by spiralham** [comment] 2023-04-27 19:28
Recently some [Dashboard](https://github.com/walkxcode/dashboard-icons) icons were updated, and some of the more narrow/taller icons are throwing off the layout.  Is there a way to set a max height to force consistency? (Firewalla & Portainer examples below)

<img width="436" alt="Screenshot 2023-04-27 at 3 20 42 PM" src="https://user-images.githubusercontent.com/7275942/234970788-ee28e8ce-505b-48f5-aa37-84bb4df7a78f.png">

<img width="235" alt="Screenshot 2023-04-27 at 3 21 07 PM" src="https://user-images.githubusercontent.com/7275942/234970806-5c102760-263e-49b8-978b-fd7a1fe9a13c.png">

**Comment by juanmanuelbc** [comment] 2023-04-28 06:25
> Recently some [Dashboard](https://github.com/walkxcode/dashboard-icons) icons were updated, and some of the more narrow/taller icons are throwing off the layout. Is there a way to set a max height to force consistency? (Firewalla & Portainer examples below)
> 
> <img alt="Screenshot 2023-04-27 at 3 20 42 PM" width="436" src="https://user-images.githubusercontent.com/7275942/234970788-ee28e8ce-505b-48f5-aa37-84bb4df7a78f.png">
> 
> <img alt="Screenshot 2023-04-27 at 3 21 07 PM" width="235" src="https://user-images.githubusercontent.com/7275942/234970806-5c102760-263e-49b8-978b-fd7a1fe9a13c.png">

It should be solved in next release thanks to this PR: https://github.com/benphelps/homepage/pull/1405...

**Comment by viharm** [comment] 2023-05-06 09:25
Is anyone having an issue where the icons in the bookmarks are vertically misaligned? I use dashboard icons.
![image](https://user-images.githubusercontent.com/2663937/236615636-70f1483e-a0d3-4c30-871e-1c8ca6fdf2c6.png)

This does not happen with mdi-icons

**Comment by ForsakenRei** [comment] 2023-05-07 22:08
I noticed all my bookmark icons shifted down a few px as well. It seems as long as I'm not using mdi-icons, both dashboard icons and custom icon will have this mis-align issue.

**Comment by JeWe37** [comment] 2023-05-14 11:48
I have been having layout issues mostly due to some widgets requiring two rows for the names of the fields within them and others just one. It would be nice if one could adjust the names of the fields independently of the translation. That way one could shorten fields as needed rather than being tied to the existing translations. I would assume that this should be possible to implement through the existing translation engine comparatively easily?

**Comment by aries223** [comment] 2023-05-18 16:16
> > My layout keeps reverting back to columns even when my settings.yaml indicate rows. If I just open the file and resave it, it will revert back to rows. Here is my settings.yaml file (renamed to txt so I could upload). I've also attached 2 files showing the difference.
> > ![Screenshot 2023-01-29 071140](https://user-images.githubusercontent.com/16128402/215328704-923412c2-0d17-4660-814d-79837ef00a73.png) ![Screenshot 2023-01-29 071547](https://user-images.githubusercontent.com/16128402/215328703-737d2640-7b7d-4066-b7a4-46a13ef836e5.png)
> > [settings.txt](https://github.com/benphelps/homepage/files/10529823/settings.txt)
> 
> Came here to report this as well. It keeps happening.

Same issue here after updating to v0.6.19 (be7aa58, May 17, 2023). Never had the issue before updating. Have to hit the 'refresh' button on the page to get it to reset.

**Comment by libook** [comment] 2023-05-23 04:00
Need anyway to load custom CSS and JS.

**Comment by libook** [comment] 2023-05-23 04:07
A unified layout scheme for services, widgets and bookmarks may be the more flexible way to go.
Adding widgets to a service may increase the height of the service component, it would save a lot of screen space if there was a dynamic layout method that could fill the gaps to the left and right of the tall component.

**Closed** 2023-05-23 10:28 UTC
