### ISSUE TITLE
[Bug] Ping should support basic auth

### ISSUE THREAD

**Issue by Falklian** [benphelps/homepage#939] opened 2023-02-04 20:36 UTC
### Description

I'm currently setting up Homepage in my homelab (awesome app, by the way) and when trying to use `ping` with my Traefik dashboard protected by basic auth, I get a `HTTP 401` status back

Crafting the URL like so:

`https://username:password@traefik.mydomain.com`

Considering the Traefik widget works with basic auth passing a username and password, it would be great if `ping` did as well

### Steps to reproduce

1. Create a service for Traefik in `services.yml`
2. Add a `ping` directive that includes passing username/password for basic auth (example above)
3. Save and wait for Homepage to refresh/manually refresh
4. A `401` error badge should show on the widget

### homepage version

v0.6.6

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment] 2023-02-04 22:01
Closed as a duplicate of #629

**Closed by shamoon** 2023-02-04 22:01 UTC
Labels: bug
