### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JLCode-tech** [benphelps/homepage#546] opened 2022-11-23 03:30 UTC
### Description

Currently getting an issue with unifi service widget and widget when homepage is deployed on Pi4. 
![image](https://user-images.githubusercontent.com/57122151/203464113-f61356f1-effb-49e5-8f91-2bd3bee00b24.png)

### Steps to reproduce

Running Raspberry Pi4 - Ubuntu 22.04.1 Podman as CE. Using the following command:
podman run -d -p 3000:3000 --name homepage --restart=always --privileged -v /run/podman/podman.sock:/var/run/docker.sock -v homepage:/app/config ghcr.io/benphelps/homepage:latest.

Configured services.yaml with the following except:
    - Unifi Controller:
        href: https://unifi.luciatech.io/
        icon: unifi-controller.png
        description: Unifi Controller
        widget:
          type: unifi
          url: https://unifi.luciatech.io
          username: xxxxxxxx
          password: xxxxxxx

### homepage version

v0.4.18 (4ea2798, Oct 16, 2022)

### Installation method

Other (please describe above)

### Configuration

```yaml
Running Raspberry Pi4 - Ubuntu 22.04.1 Podman as CE. Using the following command:
podman run -d -p 3000:3000 --name homepage --restart=always --privileged -v /run/podman/podman.sock:/var/run/docker.sock -v homepage:/app/config ghcr.io/benphelps/homepage:latest.
```

**Comment by shamoon** [comment] 2022-11-23 03:32
if you are running the controller in docker (which I think you are) this is a duplicate of #398, #394, #411

**Closed by shamoon** 2022-11-23 03:32 UTC
Labels: bug

**Comment by JLCode-tech** [comment] 2022-11-23 03:48
Running on Podman , not docker.

**Comment by shamoon** [comment] 2022-11-23 04:20
Yea I mean as opposed to running a unifi OS device. I think should be the same for podman but to be fair havent had anyone test that yet. If you want to, its currently in `main` or you can wait until the next release
