### ISSUE TITLE
Latest update broke docker integration [Bug] 

### ISSUE THREAD

**Issue by Seeveen** [benphelps/homepage#695] opened 2022-12-18 10:38 UTC
### Description

i just noticed that was a new update and now docker integration is not working anymore

### Steps to reproduce

everything also  in docker.yaml looks fine and same on services.yaml 

### homepage version

latest

### Installation method

Unraid

### Configuration

`# For configuration options and examples, please see:`
`# https://gethomepage.dev/en/configs/docker/`

 `my-docker:`
  `host: 10.10.10.6`
   `port: 2375`

`# my-docker:`
`#  socket: /var/run/docker.sock`

### Container Logs

`(error: Failed to discover services, please check docker.yaml for errors or remove example entries.)`
`error: undefined`

### Other

Error: connect ECONNREFUSED 10.10.10.6:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.10.10.6',
  port: 2375
}
Listening on port 3000
[2022-12-18T10:57:32.586Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.

**Comment by shamoon** [comment] 2022-12-18 14:08
I think this is a duplicate of #691 

in that case users actually had incorrect docker configs but the previous version was falling back to default values to make it work. I’m guessing something similar here though I don’t see an example service.

Fundamentally nothing changed in this release about how it connects to docker. If 10.10.10.6 is a remote host then it’s refusing connections on port 2375 so that’s the issue.

**Closed by shamoon** 2022-12-18 14:08 UTC
Labels: bug

**Comment by Seeveen** [comment] 2022-12-18 17:15
> I think this is a duplicate of #691
> 
> in that case users actually had incorrect docker configs but the previous version was falling back to default values to make it work. I’m guessing something similar here though I don’t see an example service.
> 
> Fundamentally nothing changed in this release about how it connects to docker. If 10.10.10.6 is a remote host then it’s refusing connections on port 2375 so that’s the issue.

that  is local IP, like i say, i am running unraid and did worked before

**Comment by shamoon** [comment] 2022-12-18 19:43
A local IP like the same machine homepage is running on? If so then you wouldn’t use the IP

again, like in the linked issue I think the defaults were actually being used and you didn’t realize and so it was working almost unintentionally. the logs say it quite clearly, that host/port combo isn’t working, my guess is that’s been there all along but you didn’t notice

Can you post an example service?
