### ISSUE TITLE
[Bug] Kubernetes service discovery via annotations faulty in 0.6.30

### ISSUE THREAD

**Issue by janpfischer** [benphelps/homepage#1998] opened 2023-09-16 12:50 UTC
### Description

Hey, 

after upgrading all my Kubernetes service annotation widget's and entries stopped working. Basically my homepage is empty and not filling with the services which have homepage annotations. 

I have no services which are not done with annotations.

Before upgrading from 0.6.29 everything was fine. 

### Steps to reproduce

1. Have services with homepage annotations in Kubernetes
2. Upgrade to 0.6.30
3. No services displayed on homepage

### homepage version

0.6.30

### Installation method

Other (please describe above)

### Configuration

```yaml
Example annotations:

gethomepage.dev/enabled: "true"
gethomepage.dev/description: A E-Book library
gethomepage.dev/group: Media
gethomepage.dev/icon: calibre-web.png
gethomepage.dev/name: Calibre Web
```

### Container Logs
```
[2023-09-16T12:44:23.313Z] error: <service-helpers> TypeError: Cannot read properties of undefined (reading 'length')
    at servicesFromKubernetes (/app/.next/server/chunks/7586.js:267:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async servicesResponse (/app/.next/server/chunks/5876.js:121:127)
    at async handler (/app/.next/server/pages/api/services.js:84:12)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
```
### Browser Logs

none

### Troubleshooting

n/a

### Other

k3s v1.27.4+k3s1

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Skaronator** [comment] 2023-09-16 14:10
I got the same error but also a read-only file system error. Not sure if it existed before:

```
[2023-09-16T14:04:57.630Z] error: <service-helpers> TypeError: Cannot read properties of undefined (reading 'length')
    at servicesFromKubernetes (/app/.next/server/chunks/7586.js:267:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async servicesResponse (/app/.next/server/chunks/5876.js:121:127)
    at async handler (/app/.next/server/pages/api/services.js:84:12)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:303:20)
[2023-09-16T14:04:57.630Z] error: Failed to discover services, please check kubernetes.yaml for errors or remove example entries.
[2023-09-16T14:04:57.631Z] error: TypeError: Cannot read properties of undefined (reading 'length')
[2023-09-16T14:05:07.608Z] error: Error: EROFS: read-only file system, copyfile '/app/src/skeleton/custom.css' -> '/app/config/custom.css'
    at copyFileSync (node:fs:2969:3)
    at checkAndCopyConfig (/app/.next/server/chunks/4574.js:53:55)
    at /app/.next/server/pages/api/hash.js:74:78
    at Array.map (<anonymous>)
    at handler (/app/.next/server/pages/api/hash.js:73:26)
    at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
```

**Comment by janpfischer** [comment] 2023-09-16 14:40
I personally can't confirm that file system error since I do not use some custom.css in my configuration. So maybe this is an other error?

**Comment by shamoon** [comment] 2023-09-16 14:43
0.6.30 introduced custom.css in #1950 but yea Im not sure if its the same issue. I wonder if manually creating the file in question will help.

As for the other error, I dont run k8s so this is tough for me to debug

**Comment by shamoon** [comment] 2023-09-16 14:50
Might be https://github.com/benphelps/homepage/pull/1875

Do you guys you traefik ingress routes at all?

**Comment by janpfischer** [comment] 2023-09-16 14:57
Thanks for the link. 
I am not running traefik ingress, I am running nginx. 

But I can relate to the #1 from the author. In older versions I am getting traefik related logs too even I do not have traefik installed. As far as I understand the MR aims to eliminating those error messages as well. And since the error seems to come from the same file which was edited in this MR it might be related. 

FTR: I am getting these error messages even in older versions but it did not bothered me since they did not do any harm. 

```
  aborted: false,
  upgrade: false,
  url: '',
  method: null,
  statusCode: 403,
  statusMessage: 'Forbidden',
  client: [TLSSocket],
  _consuming: false,
  _dumped: false,
  req: [ClientRequest],
  request: [Request],
  toJSON: [Function: responseToJSON],
  caseless: [Caseless],
  body: [Object],
  [Symbol(kCapture)]: false,
  [Symbol(kHeaders)]: [Object],
  [Symbol(kHeadersCount)]: 18,
  [Symbol(kTrailers)]: null,
  [Symbol(kTrailersCount)]: 0
}
```

This log did not disapear in 0.6.31.

**Comment by shamoon** [comment] 2023-09-16 15:11
Can you try the `main` image once its done building, see https://github.com/benphelps/homepage/actions/runs/6208079370

If that doesnt work might need some help from someone actually running k8s

**Comment by janpfischer** [comment] 2023-09-16 15:25
That is helping! The error is gone and the services are back on my homepage. 

The other error still occurs and is spamming the console. But this was the case before as well.
```
[2023-09-16T15:23:31.793Z] error: <service-helpers> Error getting traefik ingresses from traefik.containo.us: 403 {
```
```
[2023-09-16T15:23:31.804Z] error: <service-helpers> Error getting traefik ingresses from traefik.io: 403 {
```

Seems like the implementation expects to have at least one traefik ingress handler installed which is not the case if you have an other ingress like nginx. 

Maybe I find the time this weekend to look into this.

**Comment by shamoon** [comment] 2023-09-16 15:28
Great! Seems like it's checking for a 404 instead of 403, would love to confirm that 403 is the correct one, but I'll change it for now.

Closed by 3cd441a45ed861715bbd9c609719fee8c18b0d3f

**Closed by shamoon** 2023-09-16 15:28 UTC
Labels: bug, unconfirmed

**Comment by janpfischer** [comment] 2023-09-16 15:41
Thanks!
I think it can be both 404 and 403. 
404 in the case the CRDs for `ingressroutes.traefik.io` and/or `ingressroutes.traefik.containo.us` simply do not exists or 403 if the serviceaccount which is created to do the API requests does not have a permission to call these CRDs. Mine does not have because I did not have traefik installed, so why granting permissions on CRD I did not have?

To confirm this I have now added those permissions to my serviceaccount with the following cluster rule (snipped) 
```
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
```

and the error message is gone. Now I expect I will get an 404 which is not logged because of the if-clause. 

I could make a MR to change that behavior but I am unsure what is the best approach because if we simply do not log 403's if traefik is installed we would not get an hint for an error in the serviceaccount configuration. Maybe I can look into if the client can check if the CRDs are installed before trying to access them in the first place. 

Sorry for opening up this again, I just wanted to tell. You can close it again.

**Comment by shamoon** [comment] 2023-09-16 16:00
Thanks for the clarification, I'll just include 403 & 404 for now, yes it might make debugging a little tougher in some instances but I think more people appreciate the clean logs.

Yes, would welcome a PR if you have the time eventually.

**Comment by wisdomdevil** [comment] 2023-09-19 19:44
> I got the same error but also a read-only file system error. Not sure if it existed before:
> 
> ```
> [2023-09-16T14:04:57.630Z] error: <service-helpers> TypeError: Cannot read properties of undefined (reading 'length')
>     at servicesFromKubernetes (/app/.next/server/chunks/7586.js:267:56)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async servicesResponse (/app/.next/server/chunks/5876.js:121:127)
>     at async handler (/app/.next/server/pages/api/services.js:84:12)
>     at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:9)
>     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
>     at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
>     at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
>     at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
>     at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:303:20)
> [2023-09-16T14:04:57.630Z] error: Failed to discover services, please check kubernetes.yaml for errors or remove example entries.
> [2023-09-16T14:04:57.631Z] error: TypeError: Cannot read properties of undefined (reading 'length')
> [2023-09-16T14:05:07.608Z] error: Error: EROFS: read-only file system, copyfile '/app/src/skeleton/custom.css' -> '/app/config/custom.css'
>     at copyFileSync (node:fs:2969:3)
>     at checkAndCopyConfig (/app/.next/server/chunks/4574.js:53:55)
>     at /app/.next/server/pages/api/hash.js:74:78
>     at Array.map (<anonymous>)
>     at handler (/app/.next/server/pages/api/hash.js:73:26)
>     at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
>     at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
>     at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
> ```

Have same problem also in 6.0.34 
<img width="338" alt="image" src="https://github.com/benphelps/homepage/assets/74432905/1480bd7d-ef6b-4d09-acd6-cd14cc4ec467">

**Comment by shamoon** [comment] 2023-09-19 22:02
I believe the first issue is fixed in `main` now, if someone can test (its building).

The other issue seems a little less obvious to me. I dont understand if thats a Kubernetes thing where the custom.css and custom.js files (which were added recently)

**Comment by shamoon** [comment] 2023-09-19 22:02
https://github.com/benphelps/homepage/actions/runs/6241347854

**Comment by Skaronator** [comment] 2023-09-21 07:18
Okay just did some digging. The issue is that the Helm Chart mounts a Kubernetes ConfigMap to `/app/config` which means that everything in `/app/config` is read only.

Best solution would be to have custom stuff in a different directory (`/app/config/custom`) or avoid copying to that directory in the first place.

**Comment by shamoon** [comment] 2023-09-21 09:05
Thanks, there are two issues here is which is confusing. One should be sorted (I think) but glad to have some insight on this one, I've been meaning to ask as I suspected it was a Kubernetes thing. See #2040

Lets leave this thread alone unless there are more comments actually related to this issue
