### ISSUE TITLE
Docker (unraid) version stop[Bug] 

### ISSUE THREAD

**Issue by vellanix** [benphelps/homepage#1665] opened 2023-07-07 13:15 UTC
### Description

Home page on docker (unraid) start, works for a a while then stop and exit.

I think the problem is that homepage cannot reach some services on the network (since they are switched off, for example the kubernetes cluster) and the LOG show the errors.

### Steps to reproduce

1. Start homepage with the config file containing unreacable kubernets cluster ip
2. homepage start
3. homepage stop and exit
4. 

### homepage version

v0.6.21 (3e01fc1, Jun 12, 2023)

### Installation method

Unraid

### Container Logs

text  error  warn  system  array  login  

[2023-07-07T13:00:37.592Z] error: <httpProxy> Error calling http://192.168.1.205:9000/...
[2023-07-07T13:00:37.592Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.205:9000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.205',
    port: 9000
  }
]
[2023-07-07T13:00:37.654Z] error: <httpProxy> Error calling http://192.168.1.202/...
[2023-07-07T13:00:37.655Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.202:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.202',
    port: 80
  }
]
[2023-07-07T13:00:37.655Z] error: <httpProxy> Error calling http://192.168.1.201/...
[2023-07-07T13:00:37.655Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.201:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.201',
    port: 80
  }
]
[2023-07-07T13:00:37.656Z] error: <httpProxy> Error calling http://192.168.1.202/...
[2023-07-07T13:00:37.656Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.202:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.202',
    port: 80
  }
]
[2023-07-07T13:00:37.656Z] error: <httpProxy> Error calling http://192.168.1.201/...
[2023-07-07T13:00:37.656Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.201:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.201',
    port: 80
  }
]
[2023-07-07T13:00:37.718Z] error: <httpProxy> Error calling https://192.168.1.203/...
[2023-07-07T13:00:37.719Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.203:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.203',
    port: 443
  }
]
[2023-07-07T13:00:37.719Z] error: <httpProxy> Error calling https://192.168.1.203/...
[2023-07-07T13:00:37.719Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.203:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.203',
    port: 443
  }
]
[2023-07-07T13:02:37.119Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
[2023-07-07T13:02:37.120Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
[2023-07-07T13:02:37.274Z] error: <kubernetesStatusService> Error getting pods: NaN undefined undefined
[2023-07-07T13:02:37.314Z] error: <kubernetesStatusService> Error getting pods: NaN undefined undefined

** Press ANY KEY to close this window ** 

### Troubleshooting

root@pandinas:/mnt/user/appdata/homepage# docker exec homepage ping 192.168.1.99
PING 192.168.1.99 (192.168.1.99): 56 data bytes
^C
root@pandinas:/mnt/user/appdata/homepage# 
root@pandinas:/mnt/user/appdata/homepage# docker exec homepage ping 192.168.1.202
PING 192.168.1.202 (192.168.1.202): 56 data bytes
^C
root@pandinas:/mnt/user/appdata/homepage# 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment] 2023-07-07 14:30
this is a duplicate of https://github.com/benphelps/homepage/issues/1609 which was already fixed in main and will be in the next release.

**Closed** 2023-07-07 14:30 UTC
Labels: bug, unconfirmed
