### ISSUE TITLE
[Feature Request] Support for JDownloader

### ISSUE THREAD

**Issue by update-freak** [benphelps/homepage#811] opened 2023-01-12 17:22 UTC
### Description

Hello developer,

it would be great if you could add support for the docker container for JDownloader (https://github.com/jlesage/docker-jdownloader-2) that it is possible to see the status of the current download and how many files are downloaded from the list.

**Comment by JazzFisch** [comment] 2023-01-13 04:36
Dupe of #558

**Closed by JazzFisch** 2023-01-13 04:36 UTC
Labels: enhancement
