### ISSUE TITLE
[Bug] Container stops after few seconds

### ISSUE THREAD

**Issue by ChimpGamer** [benphelps/homepage#1675] opened 2023-07-12 10:01 UTC
### Description

It just stops a few seconds after starting the container with the latest image.

### Steps to reproduce

This issue started after I updated the the latest image available today.

### homepage version

v0.6.21 (3e01fc1, Jun 12, 2023)

### Installation method

Docker

### Container Logs

Listening on port 3000
[2023-07-12T09:56:00.994Z] error: undefined
[2023-07-12T09:56:02.703Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
[2023-07-12T09:56:05.066Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
[2023-07-12T09:56:05.067Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)

### Troubleshooting

n/a

### Other

I think I'm running docker 20.10.14 (API: 1.41)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment] 2023-07-12 13:58
Please search first. 

Duplicate of https://github.com/benphelps/homepage/issues/1609 which was fixed already. You can try that in the `main` image or wait for he next release

**Closed** 2023-07-12 13:58 UTC
Labels: duplicate
